name: Feature request
description: Suggest an idea for PDFKit.app
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Feature requests are welcome. Please keep the “local-only processing”
        principle in mind.

  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false

